# Generated by Django 4.1.7 on 2023-04-03 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 3, 17, 10, 41, 35938, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
