# Generated by Django 4.1.7 on 2023-04-04 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0002_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 4, 12, 21, 2, 492910, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
