# Generated by Django 4.1.7 on 2023-04-14 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0004_alter_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 14, 11, 37, 2, 171771, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
