# Generated by Django 4.1.7 on 2023-04-20 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0006_alter_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 20, 13, 9, 53, 260388, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
