# Generated by Django 4.1.7 on 2023-05-17 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0007_alter_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 16, 15, 32, 25, 114303, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
