# Generated by Django 4.1.7 on 2023-05-22 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0009_alter_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 21, 7, 24, 55, 46410, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
