# Generated by Django 4.1.7 on 2023-05-27 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0012_alter_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 26, 19, 55, 34, 301350, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
