# Generated by Django 4.1.7 on 2023-05-28 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0013_alter_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 27, 14, 35, 24, 652161, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
