# Generated by Django 4.1.7 on 2023-06-14 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0014_alter_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 14, 10, 12, 17, 153870, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("free", "A"),
                    ("price_1N8e0kSJstE3ZNVNLmyt8xpP", "B"),
                    ("price_1N8e1bSJstE3ZNVNwgCZ4sKL", "C"),
                    ("price_1N8e2BSJstE3ZNVN3ceChJtq", "D"),
                ],
                default="free",
                max_length=100,
            ),
        ),
    ]
