# Generated by Django 4.1.7 on 2023-06-14 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0016_alter_subscription_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 14, 10, 37, 37, 930768, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
