# Generated by Django 4.1.7 on 2023-06-14 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0020_alter_subscription_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 14, 11, 35, 1, 976421, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("price_1NIqyoSJstE3ZNVNgNzVWHAc", "A"),
                    ("price_1NIr2TSJstE3ZNVNuK1U5LsH", "A"),
                    ("price_1N8e0kSJstE3ZNVNLmyt8xpP", "B"),
                    ("price_1N8e0kSJstE3ZNVNzjjm5OFl", "B"),
                    ("price_1N8e1bSJstE3ZNVNwgCZ4sKL", "C"),
                    ("price_1N8e1bSJstE3ZNVNW6LQCFiH", "C"),
                    ("price_1N8e2BSJstE3ZNVN3ceChJtq", "D"),
                    ("price_1N8e2BSJstE3ZNVNcl64vI9B", "D"),
                ],
                default="price_1NIqyoSJstE3ZNVNgNzVWHAc",
                max_length=100,
            ),
        ),
    ]
