# Generated by Django 4.1.7 on 2023-06-14 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0021_alter_subscription_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 14, 11, 44, 39, 637709, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
