# Generated by Django 4.1.7 on 2023-06-16 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0023_alter_subscription_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 16, 14, 6, 54, 872018, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("A", "A"),
                    ("price_1N8e0kSJstE3ZNVNLmyt8xpP", "B"),
                    ("price_1N8e0kSJstE3ZNVNzjjm5OFl", "B"),
                    ("price_1N8e1bSJstE3ZNVNwgCZ4sKL", "C"),
                    ("price_1N8e1bSJstE3ZNVNW6LQCFiH", "C"),
                    ("price_1N8e2BSJstE3ZNVN3ceChJtq", "D"),
                    ("price_1N8e2BSJstE3ZNVNcl64vI9B", "D"),
                ],
                default="A",
                max_length=100,
            ),
        ),
    ]
