# Generated by Django 4.1.7 on 2023-06-16 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0024_alter_subscription_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 16, 14, 44, 42, 494064, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
