# Generated by Django 4.1.7 on 2023-05-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_customuser_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conductuser",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
