# Generated by Django 4.1.7 on 2023-04-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servey_quiz_form", "0002_alter_form_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="code",
            field=models.CharField(
                max_length=30, unique="o2vOyYXdsVMkKCwVvuGrW0zyN88qd7"
            ),
        ),
        migrations.AlterField(
            model_name="responses",
            name="responder_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
