# Generated by Django 4.1.7 on 2023-04-14 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("servey_quiz_form", "0003_alter_form_code_alter_responses_responder_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="code",
            field=models.CharField(
                max_length=30, unique="56U9foRQeUPpSEtNGwZgZ9kRocay6t"
            ),
        ),
        migrations.AlterField(
            model_name="responses",
            name="responder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
