# Generated by Django 4.1.7 on 2023-04-14 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("servey_quiz_form", "0004_alter_form_code_alter_responses_responder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="code",
            field=models.CharField(
                max_length=30, unique="LtGgiq5NRjeHQnPgvZ90X1XNbrbfUQ"
            ),
        ),
        migrations.AlterField(
            model_name="responses",
            name="responder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responder",
                to="accounts.userquiz",
            ),
        ),
    ]
