# Generated by Django 4.1.7 on 2023-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servey_quiz_form", "0005_alter_form_code_alter_responses_responder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="code",
            field=models.CharField(
                max_length=30, unique="ui6vt0pwoykjrN5I2D19sLIoxI7E4F"
            ),
        ),
    ]
