# Generated by Django 4.1.7 on 2023-05-22 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_conductuser_stripe_customer_id"),
        ("servey_quiz_form", "0008_alter_form_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="available_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="form",
            name="exam_duration",
            field=models.PositiveIntegerField(
                blank=True, help_text="Duration of the exam in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="form",
            name="form_valid",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="form",
            name="code",
            field=models.CharField(
                max_length=30, unique="GyQBs8WnJ85XIsa0067viXvhyy0fJy"
            ),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_code", models.CharField(max_length=20)),
                ("score", models.IntegerField()),
                ("total_score", models.IntegerField()),
                ("percentage", models.FloatField()),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_responder",
                        to="accounts.userquiz",
                    ),
                ),
                (
                    "result_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_to",
                        to="servey_quiz_form.form",
                    ),
                ),
            ],
        ),
    ]
