# Generated by Django 4.1.7 on 2023-06-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servey_quiz_form", "0014_alter_form_code_alter_result_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="code",
            field=models.CharField(
                max_length=30, unique="dEjyghtY46n6gcTkrRnQVf176F1vBa"
            ),
        ),
    ]
