# Generated by Django 4.1.7 on 2023-06-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("servey_quiz_form", "0015_alter_form_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="code",
            field=models.CharField(
                max_length=30, unique="4nMRMIDdXxQZfUgaOMAAAfHxZ5Wu3V"
            ),
        ),
    ]
